### ISSUE TITLE
Setting up database source

### ISSUE THREAD

**Issue by hsdhillon** [josegonzalez/cakephp-environments#11]
Hi,

Thanks for the great plugin!

I am trying to setup database source using this plugin but having some problem getting that to work. I am using following format in my development environment's $config array.

'Datasources.default.className' => 'Cake\Database\Connection',
'Datasources.default.driver' => 'Cake\Database\Driver\Mysql',

Is this the correct approach or should I be doing something else?

**Comment by hsdhillon** [comment]
Never mind.. I figured it out and instead using $config, I used $callable and defined following in anonymous function...

```
    ConnectionManager::config('default', [
        'className' => 'Cake\Database\Connection',
        'driver' => 'Cake\Database\Driver\Mysql',
        'persistent' => false,
        'host' => 'localhost',
        'username' => 'test2',
        'password' => 'XiGvMPUSH3',
        'database' => 'testdb',
        'encoding' => 'utf8',
        'timezone' => 'UTC',
        'cacheMetadata' => true,
    ]);
```

**Comment by josegonzalez** [comment]
Yep, thats more or less how it should be done.
